AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'gemfiles/vendor/**/*'
    - 'lib/smart_paginate/version.rb'
    - 'vendor/**/*'

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/BlockComments:
  Exclude:
    - 'spec/**/*.rb'

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false
