require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'gemfiles/vendor/**/*'
    - 'lib/smart_paginate/version.rb'
    - 'vendor/**/*'

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Max: 11

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 2

Style/BlockComments:
  Exclude:
    - 'spec/**/*.rb'

Style/Documentation:
  Enabled: false

Style/RedundantSelf:
  Enabled: false
