language: ruby
sudo: false
cache: bundler
before_install:
  - gem update --system
  - gem update bundler
rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
gemfile:
  - gemfiles/Gemfile.active_record-4.0
  - gemfiles/Gemfile.active_record-4.1
  - gemfiles/Gemfile.active_record-4.2
  - gemfiles/Gemfile.active_record-5.0
  - gemfiles/Gemfile.active_record-5.1
  - gemfiles/Gemfile.active_record-5.2
matrix:
  exclude:
    - rvm: 2.4.4
      gemfile: gemfiles/Gemfile.active_record-4.0
    - rvm: 2.4.4
      gemfile: gemfiles/Gemfile.active_record-4.1
    - rvm: 2.5.1
      gemfile: gemfiles/Gemfile.active_record-4.0
    - rvm: 2.5.1
      gemfile: gemfiles/Gemfile.active_record-4.1
