language: ruby
sudo: false
cache: bundler
before_install:
  - gem update --system
  - gem install bundler
rvm:
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
gemfile:
  - gemfiles/Gemfile.active_record-4.0
  - gemfiles/Gemfile.active_record-4.1
  - gemfiles/Gemfile.active_record-4.2
  - gemfiles/Gemfile.active_record-5.0
  - gemfiles/Gemfile.active_record-5.1
  - gemfiles/Gemfile.active_record-5.2
  - gemfiles/Gemfile.active_record-6.0
  - gemfiles/Gemfile.active_record-edge
matrix:
  exclude:
    - rvm: 2.4.9
      gemfile: gemfiles/Gemfile.active_record-4.0
    - rvm: 2.5.7
      gemfile: gemfiles/Gemfile.active_record-4.0
    - rvm: 2.6.5
      gemfile: gemfiles/Gemfile.active_record-4.0
    - rvm: 2.7.0
      gemfile: gemfiles/Gemfile.active_record-4.0
    - rvm: 2.4.9
      gemfile: gemfiles/Gemfile.active_record-4.1
    - rvm: 2.5.7
      gemfile: gemfiles/Gemfile.active_record-4.1
    - rvm: 2.6.5
      gemfile: gemfiles/Gemfile.active_record-4.1
    - rvm: 2.7.0
      gemfile: gemfiles/Gemfile.active_record-4.1
    - rvm: 2.7.0
      gemfile: gemfiles/Gemfile.active_record-4.2
    - rvm: 2.3.8
      gemfile: gemfiles/Gemfile.active_record-6.0
    - rvm: 2.4.9
      gemfile: gemfiles/Gemfile.active_record-6.0
    - rvm: 2.3.8
      gemfile: gemfiles/Gemfile.active_record-edge
    - rvm: 2.4.9
      gemfile: gemfiles/Gemfile.active_record-edge
