language: ruby
sudo: false
cache: bundler
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
gemfile:
  - gemfiles/Gemfile.active_record-4.0
  - gemfiles/Gemfile.active_record-4.1
  - gemfiles/Gemfile.active_record-4.2
  - gemfiles/Gemfile.active_record-5.0
  - gemfiles/Gemfile.active_record-5.1
matrix:
  exclude:
    - rvm: 2.4.1
      gemfile: gemfiles/Gemfile.active_record-4.0
    - rvm: 2.4.1
      gemfile: gemfiles/Gemfile.active_record-4.1
