name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7', '3.0', '3.1', '3.2', '3.3', '3.4']
        gemfile:
          - gemfiles/Gemfile.active_record-6.0
          - gemfiles/Gemfile.active_record-6.1
          - gemfiles/Gemfile.active_record-7.0
          - gemfiles/Gemfile.active_record-7.1
          - gemfiles/Gemfile.active_record-7.2
          - gemfiles/Gemfile.active_record-8.0
          - gemfiles/Gemfile.active_record-edge
        exclude:
          - ruby-version: 3.0
            gemfile: gemfiles/Gemfile.active_record-6.0
          - ruby-version: 3.1
            gemfile: gemfiles/Gemfile.active_record-6.0
          - ruby-version: 3.2
            gemfile: gemfiles/Gemfile.active_record-6.0
          - ruby-version: 3.3
            gemfile: gemfiles/Gemfile.active_record-6.0
          - ruby-version: 3.4
            gemfile: gemfiles/Gemfile.active_record-6.0
          - ruby-version: 3.2
            gemfile: gemfiles/Gemfile.active_record-6.1
          - ruby-version: 3.3
            gemfile: gemfiles/Gemfile.active_record-6.1
          - ruby-version: 3.4
            gemfile: gemfiles/Gemfile.active_record-6.1
          - ruby-version: 3.2
            gemfile: gemfiles/Gemfile.active_record-7.0
          - ruby-version: 3.3
            gemfile: gemfiles/Gemfile.active_record-7.0
          - ruby-version: 3.4
            gemfile: gemfiles/Gemfile.active_record-7.0
          - ruby-version: 2.7
            gemfile: gemfiles/Gemfile.active_record-7.2
          - ruby-version: 3.0
            gemfile: gemfiles/Gemfile.active_record-7.2
          - ruby-version: 2.7
            gemfile: gemfiles/Gemfile.active_record-8.0
          - ruby-version: 3.0
            gemfile: gemfiles/Gemfile.active_record-8.0
          - ruby-version: 3.1
            gemfile: gemfiles/Gemfile.active_record-8.0
          - ruby-version: 2.7
            gemfile: gemfiles/Gemfile.active_record-edge
          - ruby-version: 3.0
            gemfile: gemfiles/Gemfile.active_record-edge
          - ruby-version: 3.1
            gemfile: gemfiles/Gemfile.active_record-edge
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake
